version: '3.8'
services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  pdf-upload:
    build: ./server/pdf-upload
    volumes:
      - ./server/pdf-upload/uploads:/app/uploads
    environment:
      - NODE_ENV=development
      - GOOGLE_APPLICATION_CREDENTIALS=/app/keys/ai-pdf-translation-service-10642063de1f.json
    depends_on:
      - ocr

  ocr:
    build: ./server/ocr
    environment:
      - NODE_ENV=development
      - GOOGLE_APPLICATION_CREDENTIALS=/app/keys/ai-pdf-translation-service-10642063de1f.json
    depends_on:
      - translation

  translation:
    build: ./server/translation
    environment:
      - NODE_ENV=development
      - GOOGLE_APPLICATION_CREDENTIALS=/app/keys/ai-pdf-translation-service-10642063de1f.json
